# ctest: every `import X` in <QML_DIR>/*.qml must be listed in MAP (deps/qml-runtime.txt),
# so the runtime package list cannot fall behind the code (M1 contracts §6.18).
# Usage: cmake -DQML_DIR=<dir> -DMAP=<deps/qml-runtime.txt> -DSKIP=<Own.Module,Other> -P check_qml_imports.cmake
cmake_minimum_required(VERSION 3.24)
file(STRINGS "${MAP}" map_lines REGEX "^[A-Za-z]")
set(known "")
foreach(line IN LISTS map_lines)
  string(REGEX MATCH "^[^ \t]+" module "${line}")
  list(APPEND known "${module}")
endforeach()
string(REPLACE "," ";" skip "${SKIP}")
file(GLOB qml_files "${QML_DIR}/*.qml")
set(missing "")
foreach(qml_file IN LISTS qml_files)
  file(STRINGS "${qml_file}" imports REGEX "^import ")
  foreach(import_line IN LISTS imports)
    string(REGEX REPLACE "^import ([A-Za-z.]+).*" "\\1" module "${import_line}")
    if(NOT module IN_LIST skip AND NOT module IN_LIST known)
      list(APPEND missing "${module} (${qml_file})")
    endif()
  endforeach()
endforeach()
if(missing)
  message(FATAL_ERROR "QML imports missing from ${MAP}: ${missing}")
endif()
message(STATUS "all QML imports in ${QML_DIR} are listed in ${MAP}")
