# ctest (design §3.1): the control-socket channels jarvis-shell hard-codes must
# be exactly the ones packages/wire/os-control.json lists (which
# packages/desktop/src/daemon/os/os-control-json.test.ts keeps equal to
# @jarvis/wire). Requests are the `request(u"<ch>"` calls, pushes the
# `channel == u"<ch>"` checks in ShellController.
# Usage: cmake -DSRC_DIR=<os/shell/src> -DWIRE_JSON=<packages/wire/os-control.json> -P check_control_channels.cmake
cmake_minimum_required(VERSION 3.24)

file(READ "${WIRE_JSON}" wire)
function(json_list key out)
  string(JSON n LENGTH "${wire}" ${key})
  set(items "")
  if(n GREATER 0)
    math(EXPR last "${n} - 1")
    foreach(i RANGE ${last})
      string(JSON item GET "${wire}" ${key} ${i})
      list(APPEND items "${item}")
    endforeach()
  endif()
  list(SORT items)
  set(${out} "${items}" PARENT_SCOPE)
endfunction()
json_list(requests wire_requests)
json_list(pushes wire_pushes)

file(GLOB_RECURSE sources "${SRC_DIR}/*.cpp" "${SRC_DIR}/*.h")
set(shell_requests "")
set(shell_pushes "")
foreach(source IN LISTS sources)
  file(READ "${source}" text)
  string(REGEX MATCHALL "request\\(u\"[^\"]+\"" calls "${text}")
  foreach(call IN LISTS calls)
    string(REGEX REPLACE "^request\\(u\"([^\"]+)\"$" "\\1" ch "${call}")
    list(APPEND shell_requests "${ch}")
  endforeach()
  string(REGEX MATCHALL "channel == u\"[^\"]+\"" checks "${text}")
  foreach(check IN LISTS checks)
    string(REGEX REPLACE "^channel == u\"([^\"]+)\"$" "\\1" ch "${check}")
    list(APPEND shell_pushes "${ch}")
  endforeach()
endforeach()
list(REMOVE_DUPLICATES shell_requests)
list(REMOVE_DUPLICATES shell_pushes)
list(SORT shell_requests)
list(SORT shell_pushes)

set(errors "")
if(NOT shell_requests STREQUAL wire_requests)
  string(APPEND errors "\n  requests: shell [${shell_requests}]\n            wire  [${wire_requests}]")
endif()
if(NOT shell_pushes STREQUAL wire_pushes)
  string(APPEND errors "\n  pushes:   shell [${shell_pushes}]\n            wire  [${wire_pushes}]")
endif()
if(errors)
  message(FATAL_ERROR "jarvis-shell channels differ from ${WIRE_JSON}:${errors}")
endif()
message(STATUS "jarvis-shell uses exactly the channels in os-control.json")
