# ctest: every `import X` in src/qml/*.qml must be listed in deps/qml-runtime.txt,
# so the published runtime package list cannot fall behind the code.
# Usage: cmake -DQML_DIR=<src/qml> -DMAP=<deps/qml-runtime.txt> -P check_qml_imports.cmake
cmake_minimum_required(VERSION 3.24)
file(STRINGS "${MAP}" map_lines REGEX "^[A-Za-z]")
set(known "")
foreach(line IN LISTS map_lines)
  string(REGEX MATCH "^[^ \t]+" module "${line}")
  list(APPEND known "${module}")
endforeach()
file(GLOB qml_files "${QML_DIR}/*.qml")
set(missing "")
foreach(qml_file IN LISTS qml_files)
  file(STRINGS "${qml_file}" imports REGEX "^import ")
  foreach(import_line IN LISTS imports)
    string(REGEX REPLACE "^import ([A-Za-z.]+).*" "\\1" module "${import_line}")
    if(NOT module STREQUAL "Jarvis.Shell" AND NOT module IN_LIST known)
      list(APPEND missing "${module} (${qml_file})")
    endif()
  endforeach()
endforeach()
if(missing)
  message(FATAL_ERROR "QML imports missing from deps/qml-runtime.txt: ${missing}")
endif()
message(STATUS "all QML imports are listed in deps/qml-runtime.txt")
