// Shell integration for the Terminal tab under bash — the sibling of
// zsh-integration.ts, and the reason the Terminal tab is not a plain terminal
// on Linux, where bash is the default login shell.
//
// The marks, the command log and the contract are identical to zsh's. Only
// the installation mechanism differs, and that difference is the whole of
// what is interesting here — see installBashIntegration.

import { JARVIS_COMMAND_LOG_ENV } from "./zsh-integration.js";

/** The wrapper's file name inside the Jarvis-owned directory. One file, not
 *  four: bash has no ZDOTDIR, so there is no chain of startup files to
 *  mirror. */
const WRAPPER_NAME = "bashrc";

/** The personal profile files a bash login shell considers, in its own order.
 *  It reads the FIRST that exists and stops — reading more than one is not
 *  what bash does, and doubles whatever PATH edits they share. */
const PROFILE_FILES = [".bash_profile", ".bash_login", ".profile"] as const;

/**
 * bash, by the name its own argv[0] carries.
 *
 * `-bash` is how a login shell spells itself, exactly as `-zsh` does.
 */
export function isBash(shell: string | undefined): boolean {
  if (shell === undefined || shell === "") return false;
  const name = shell.slice(shell.lastIndexOf("/") + 1);
  return name === "bash" || name === "-bash";
}

/** A path as shell source: single-quoted, with any embedded quote closed,
 *  escaped and reopened. Nothing inside single quotes is expanded, so this is
 *  safe for a home directory containing a space, a `$` or a backtick. */
function quote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

/**
 * What `bash -l` reads, done by hand.
 *
 * The wrapper replaces `-l` rather than supplementing it, because bash
 * honours `--rcfile` only for an interactive *non-login* shell: a login bash
 * ignores it entirely and reads the profile files instead, so the hook would
 * silently never install. The other two ways in are worse — BASH_ENV applies
 * only to non-interactive shells, and a PROMPT_COMMAND exported through the
 * environment is overwritten by any ~/.bashrc that assigns it, which every
 * major distribution's default does.
 *
 * So this reproduces a login shell's own reading: /etc/profile, then the
 * first of ~/.bash_profile, ~/.bash_login, ~/.profile — and then stops.
 *
 * It deliberately does not source ~/.bashrc. A login shell does not either;
 * distributions that want it there source it from the profile, and doing it
 * again here would run their PATH edits twice.
 */
function chain(home: string): string[] {
  const candidates = PROFILE_FILES.map((name) => quote(`${home}/${name}`)).join(" ");
  return [
    "# Generated by Jarvis. Edits are overwritten; your own dotfiles are never modified.",
    "if [ -r /etc/profile ]; then . /etc/profile; fi",
    `for __jarvis_profile in ${candidates}; do`,
    '  if [ -r "$__jarvis_profile" ]; then . "$__jarvis_profile"; break; fi',
    "done",
    "unset __jarvis_profile",
  ];
}

/**
 * The OSC 133 hooks, and the command log that gives ranking its directory
 * affinity. The same marks the zsh wrapper emits, by whichever of two
 * mechanisms this shell allows.
 *
 * `A` marks the start of the prompt, `B` its end — the column the typed
 * command begins at, which is the whole reason for this file. `C` says a
 * command is running, so the dropdown closes; `D` carries its exit status.
 * Those four are emitted by __jarvis_emit_preexec and __jarvis_emit_precmd,
 * which both paths below share.
 *
 * The paths exist because bash has no preexec of its own, and the DEBUG trap
 * that stands in for one is a single global slot. If bash-preexec already
 * holds it — Atuin ships it, so do iTerm2's shell integration and several
 * distributions' profile.d — then setting our own trap here does not chain,
 * it clobbers, and bash-preexec's own lazy install clobbers back on the first
 * PROMPT_COMMAND. That cost the first command of every session, observably.
 * So when it is present we register through its arrays, which is the
 * supported way in, and when it is not we take the trap ourselves.
 *
 * The prompt-end mark is appended to whatever PS1 the user's own rc left
 * behind, never assigned over it — and wrapped in \[ \], which tell bash
 * these bytes occupy no columns. Unwrapped, bash counts them as printable and
 * every line that reaches the right margin wraps in the wrong column.
 *
 * Everything here is guarded or non-fatal: a log that cannot be written
 * leaves a working terminal with no autocomplete, which is the failure mode
 * this design insists on.
 */
function hooks(): string[] {
  const log = JARVIS_COMMAND_LOG_ENV;
  return [
    "",
    "if [[ $- == *i* ]]; then",
    "  __jarvis_osc() { printf '\\e]133;%s\\a' \"$1\"; }",
    "  __jarvis_osc7() { printf '\\e]7;file://%s\\a' \"$1\"; }",
    "",
    "  # The two marks, independent of how this shell manages to call them.",
    "  __jarvis_emit_preexec() {",
    '    __jarvis_osc "C;${1}"',
    '    if [[ -n "$' + log + '" ]]; then',
    // EPOCHSECONDS is bash 5.0+; `date` covers anything older. The log is the
    // only source that records a cwd, which is what directory affinity ranks
    // on — losing it on an old bash would quietly halve the feature.
    '      printf \'%s\\t%s\\t%s\\n\' "${EPOCHSECONDS:-$(date +%s)}" "$PWD" "$1" >> "$' +
      log +
      '" 2>/dev/null',
    "    fi",
    "  }",
    "  __jarvis_emit_precmd() {",
    '    __jarvis_osc "D;$1"',
    '    __jarvis_osc7 "$PWD"',
    "    __jarvis_osc 'A'",
    "  }",
    "",
    '  if [[ -n "${__bp_imported:-}" ]]; then',
    "    # bash-preexec is already here — shipped by Atuin, iTerm2's shell",
    "    # integration, and several distributions' profile.d. It owns the DEBUG",
    "    # trap, and installs it lazily on the first PROMPT_COMMAND, which is",
    "    # after this file has run. A raw trap of our own is therefore",
    "    # overwritten a moment after it is set, and the first command of every",
    "    # session is lost before its chaining takes over. Registering through",
    "    # its own arrays is the supported way in, and it is exact.",
    '    __jarvis_bp_preexec() { __jarvis_emit_preexec "$1"; }',
    '    __jarvis_bp_precmd() { __jarvis_emit_precmd "${__bp_last_ret_value:-$?}"; }',
    "    preexec_functions+=(__jarvis_bp_preexec)",
    "    precmd_functions+=(__jarvis_bp_precmd)",
    "  else",
    "    # No bash-preexec: the DEBUG trap stands in for the preexec bash does",
    "    # not have. DEBUG fires before *every* simple command, including each",
    "    # one inside PROMPT_COMMAND, so __jarvis_armed lets exactly the first",
    "    # command after a prompt through and then disarms.",
    "    #",
    "    # Arming is its own PROMPT_COMMAND entry, appended last while the marks",
    "    # are emitted first, so anything else already in PROMPT_COMMAND runs",
    "    # between the two and cannot consume the arm. It starts at 0 because",
    "    # the setup lines below are themselves simple commands.",
    "    __jarvis_armed=0",
    "    __jarvis_preexec() {",
    // Completion runs commands through DEBUG too, and none of them are the
    // user's.
    '      [[ -n "$COMP_LINE" ]] && return',
    "      (( __jarvis_armed )) || return",
    "      __jarvis_armed=0",
    '      __jarvis_emit_preexec "$BASH_COMMAND"',
    "    }",
    "    __jarvis_precmd() {",
    "      local __jarvis_exit=$?",
    '      __jarvis_emit_precmd "$__jarvis_exit"',
    "      return $__jarvis_exit",
    "    }",
    // Status-preserving: a bare return here would hand the user's own prompt
    // a 0 in place of whatever their command actually exited with.
    "    __jarvis_arm() {",
    "      local __jarvis_status=$?",
    "      __jarvis_armed=1",
    "      return $__jarvis_status",
    "    }",
    "    trap '__jarvis_preexec' DEBUG",
    // bash 5.1 made PROMPT_COMMAND assignable as an array, and a string
    // prepend against one would keep only its first element — silently
    // dropping whatever else the user's rc had queued there.
    "    if [[ ${BASH_VERSINFO[0]} -gt 5 || ( ${BASH_VERSINFO[0]} -eq 5 && ${BASH_VERSINFO[1]} -ge 1 ) ]] && [[ ${PROMPT_COMMAND@a} == *a* ]]; then",
    '      PROMPT_COMMAND=(__jarvis_precmd "${PROMPT_COMMAND[@]}" __jarvis_arm)',
    "    else",
    '      PROMPT_COMMAND="__jarvis_precmd${PROMPT_COMMAND:+; $PROMPT_COMMAND}; __jarvis_arm"',
    "    fi",
    "  fi",
    "",
    '  PS1="${PS1}\\[\\e]133;B\\a\\]"',
    "fi",
    "",
    "# Leaves $_ set to something.",
    "#",
    '# bash-preexec\'s DEBUG trap is installed as `__bp_preexec_invoke_exec "$_"`',
    "# and dereferences what it receives with ${...:?}, so an empty $_ at the",
    "# first prompt prints `__bp_last_argument_prev_command: parameter null or",
    "# not set` into the user's terminal and abandons that command's preexec.",
    "# A login shell always has one — its last profile line left it — but a",
    "# shell started with --rcfile can reach the prompt with $_ still empty.",
    "# The colon builtin sets it and does nothing else.",
    ": jarvis",
    "",
  ];
}

/**
 * The wrapper rcfile's whole text.
 *
 * Pure — it takes the user's home directory and returns text. The chaining it
 * produces is the single riskiest mechanical piece of this feature, which is
 * why it is a value a test can read rather than something only a real login
 * shell could reveal.
 */
export function bashWrapperFile(home: string): string {
  return `${[...chain(home), ...hooks()].join("\n")}\n`;
}

export type BashIntegrationDeps = {
  /** The user's login shell — `$SHELL`. This installer is bash-only. */
  shell: string | undefined;
  /** `terminal.completion.enabled`. False installs nothing at all: one
   *  switch, no half-state. */
  enabled: boolean;
  /** Where the wrapper is written — Jarvis's own directory, never the
   *  user's. */
  dir: string;
  /** The user's home directory, whose profile files the wrapper chains to. */
  home: string;
  write: (path: string, contents: string) => Promise<void>;
};

/**
 * Writes the wrapper and returns the path to hand the child shell as
 * `--rcfile` — or undefined when there is to be no integration.
 *
 * Undefined is a first-class outcome, not an error: disabled, not bash, or a
 * file that could not be written all mean the same thing to the terminal,
 * which is that it behaves exactly as it does today. There is no dialog and
 * nothing logged to the user, because a failure here costs an autocomplete
 * and nothing else.
 */
export async function installBashIntegration(
  deps: BashIntegrationDeps,
): Promise<string | undefined> {
  if (!deps.enabled) return undefined;
  if (!isBash(deps.shell)) return undefined;

  const path = `${deps.dir}/${WRAPPER_NAME}`;
  try {
    await deps.write(path, bashWrapperFile(deps.home));
    return path;
  } catch {
    // No wrapper, so no rcfile, so no marks, so no dropdown.
    return undefined;
  }
}
