// Shell integration for the Terminal tab on Windows, where the shell is
// PowerShell and there is neither a ZDOTDIR to redirect nor an --rcfile to
// hand it.
//
// The marks are the ones zsh-integration.ts and bash-integration.ts emit —
// OSC 133 A/B/C/D around the prompt and the command, OSC 7 for the working
// directory — so the renderer's block splitter, chip row and completion
// dropdown need no idea which shell drew them. What differs is how a hook
// gets in: PowerShell's `prompt` is an ordinary function that can be
// wrapped, and PSReadLine lets Enter be intercepted, which is where the
// command about to run can be read before it runs.
//
// The user's own $PROFILE is never modified, and it still loads: the shell
// starts without -NoProfile, so the profile runs first and whatever prompt
// it leaves behind is the one wrapped here. The script reaches the shell as
// an encoded command rather than as a file path to execute, because a fresh
// Windows has ExecutionPolicy Restricted, under which no .ps1 runs at all —
// and asking a user to change a machine-wide security policy to get an
// autocomplete is not a trade this feature may make.

import { JARVIS_COMMAND_LOG_ENV } from "./zsh-integration.js";

/** PowerShell in either of its two spellings, with or without `.exe`. */
export function isPowerShell(shell: string | undefined): boolean {
  if (shell === undefined || shell === "") return false;
  const name = shell
    .slice(Math.max(shell.lastIndexOf("/"), shell.lastIndexOf("\\")) + 1)
    .toLowerCase()
    .replace(/\.exe$/, "");
  return name === "powershell" || name === "pwsh";
}

/**
 * The integration script, as text.
 *
 * Written for Windows PowerShell 5.1 as well as PowerShell 7: `[char]27`
 * rather than the "`e" escape 5.1 does not have, and nothing from $PSStyle.
 * Every hook is guarded — a PSReadLine that is not loaded, a log that cannot
 * be written — and leaves a working terminal with no autocomplete, the same
 * failure mode the other two installers insist on.
 *
 * The D mark carries `[int]!$?`: 0 when the last command succeeded, 1
 * otherwise. PowerShell has no single exit code for a cmdlet and
 * $LASTEXITCODE is set only by native programs, so success/failure is the
 * honest granularity — and it is all the block filter asks.
 *
 * OSC 7 carries the path exactly as PowerShell reports it, `C:\Users\…`,
 * after `file://` with no host and no percent-encoding: that is the form the
 * other two send and the form terminal-blocks.ts reads back.
 */
export function powerShellIntegrationScript(): string {
  return [
    "# Generated by Jarvis. Edits are overwritten; your own profile is never modified.",
    "",
    "# Native programs print UTF-8 and the terminal decodes UTF-8; Windows",
    "# PowerShell defaults both sides to the OEM code page, which turns an",
    "# Arabic file name in `git status` into question marks.",
    "try {",
    "  [Console]::OutputEncoding = [System.Text.Encoding]::UTF8",
    "  $OutputEncoding = [System.Text.Encoding]::UTF8",
    "} catch {}",
    "",
    "$Global:__JarvisEsc = [char]27",
    "$Global:__JarvisBel = [char]7",
    "",
    "# The prompt the profile left behind, wrapped rather than replaced: the",
    "# marks go around it, and what it draws is still theirs.",
    "if (-not (Test-Path Function:\\Global:__JarvisOriginalPrompt)) {",
    "  $Global:__JarvisOriginalPrompt = $function:prompt",
    "}",
    "",
    "function Global:prompt {",
    "  $__jarvisExit = [int](-not $?)",
    '  $__jarvisOut = "$Global:__JarvisEsc]133;D;$__jarvisExit$Global:__JarvisBel"',
    '  $__jarvisOut += "$Global:__JarvisEsc]7;file://$($ExecutionContext.SessionState.Path.CurrentLocation.ProviderPath)$Global:__JarvisBel"',
    '  $__jarvisOut += "$Global:__JarvisEsc]133;A$Global:__JarvisBel"',
    "  $__jarvisPrompt = try { & $Global:__JarvisOriginalPrompt } catch { 'PS> ' }",
    "  if ($null -eq $__jarvisPrompt -or \"$__jarvisPrompt\" -eq '') { $__jarvisPrompt = 'PS> ' }",
    '  $__jarvisOut += "$__jarvisPrompt"',
    '  $__jarvisOut += "$Global:__JarvisEsc]133;B$Global:__JarvisBel"',
    "  return $__jarvisOut",
    "}",
    "",
    "# Enter, intercepted so the command about to run can be marked (C) and",
    "# logged before PSReadLine hands it to the shell. Without PSReadLine there",
    "# is no way to see the line before it runs, and no way to offer a dropdown",
    "# on it either — so its absence costs exactly the feature.",
    "if (Get-Module -Name PSReadLine -ErrorAction SilentlyContinue) {",
    "  Set-PSReadLineKeyHandler -Key Enter -BriefDescription JarvisAcceptLine -Description 'Marks and logs the command for Jarvis, then runs it' -ScriptBlock {",
    "    param($key, $arg)",
    "    $line = $null",
    "    $cursor = $null",
    "    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)",
    "    try {",
    '      [Console]::Write("$Global:__JarvisEsc]133;C;$line$Global:__JarvisBel")',
    `      if ($env:${JARVIS_COMMAND_LOG_ENV} -and $line.Trim() -ne '') {`,
    "        $epoch = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()",
    "        $cwd = $ExecutionContext.SessionState.Path.CurrentLocation.ProviderPath",
    `        [System.IO.File]::AppendAllText($env:${JARVIS_COMMAND_LOG_ENV}, "$epoch\`t$cwd\`t$line\`n")`,
    "      }",
    "    } catch {}",
    "    [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()",
    "  }",
    "}",
    "",
  ].join("\n");
}

/**
 * The arguments that start an interactive PowerShell with the integration
 * loaded: the profile first (no -NoProfile), then the script, then a prompt
 * that stays (-NoExit).
 *
 * The script is dot-sourced from a scriptblock built out of its text rather
 * than executed as a file, and the bootstrap that does so is passed as a
 * base64 UTF-16LE `-EncodedCommand`. Neither is a file being run, so
 * ExecutionPolicy does not apply to either — and the command line stays a
 * few hundred bytes however the script grows.
 */
export function powerShellLaunchArgs(scriptPath: string | undefined): string[] {
  const args = ["-NoLogo", "-NoExit"];
  if (scriptPath === undefined) return args;
  // PowerShell's single-quoted string: the only escape is a doubled quote,
  // so a path with an apostrophe in it survives intact.
  const quoted = `'${scriptPath.replaceAll("'", "''")}'`;
  const bootstrap = `. ([scriptblock]::Create([System.IO.File]::ReadAllText(${quoted}, [System.Text.Encoding]::UTF8)))`;
  return [...args, "-EncodedCommand", Buffer.from(bootstrap, "utf16le").toString("base64")];
}

export type PowerShellIntegrationDeps = {
  /** `terminal.completion.enabled` — false installs nothing at all. */
  enabled: boolean;
  /** Where the script is written: Jarvis's own directory. */
  dir: string;
  write: (path: string, contents: string) => Promise<void>;
};

/** The script's file name inside `dir`. */
export const POWERSHELL_INTEGRATION_FILE = "jarvis-integration.ps1";

/**
 * Writes the script and returns its path, or undefined when there is to be
 * no integration — which is a first-class outcome rather than an error,
 * exactly as the other two installers treat it.
 */
export async function installPowerShellIntegration(
  deps: PowerShellIntegrationDeps,
): Promise<string | undefined> {
  if (!deps.enabled) return undefined;
  const path = `${deps.dir}\\${POWERSHELL_INTEGRATION_FILE}`;
  try {
    await deps.write(path, powerShellIntegrationScript());
    return path;
  } catch {
    return undefined;
  }
}

/** Where PSReadLine keeps the history Jarvis's completion ranks against —
 *  the Windows counterpart of ~/.zsh_history and ~/.bash_history. */
export function powerShellHistoryPath(env: NodeJS.ProcessEnv, home: string): string {
  const appData = env["APPDATA"] ?? `${home}\\AppData\\Roaming`;
  return `${appData}\\Microsoft\\Windows\\PowerShell\\PSReadLine\\ConsoleHost_history.txt`;
}
