// Shell integration for the Terminal tab, installed without ever touching
// the user's own dotfiles.
//
// Jarvis needs to know where a prompt ends and the typed command begins,
// which no amount of pattern-matching on a user-configured prompt can tell
// it. OSC 133 — the FinalTerm/iTerm2 marks that VS Code, WezTerm and Warp
// all use — carries the answer, and a shell hook is the only thing that can
// emit it.
//
// The hook is installed by pointing the child shell's ZDOTDIR at a
// Jarvis-owned directory whose startup files source the user's real ones
// and then add the hook. ~/.zshrc, ~/.zprofile and ~/.zshenv are read and
// never written.

/** The environment variable naming the file the preexec hook appends each
 *  command to. Read by the wrapper; set by shell.ts. */
export const JARVIS_COMMAND_LOG_ENV = "JARVIS_COMMAND_LOG";

/** The startup files a zsh login shell reads, in the order it reads them.
 *  All four are wrapped: chaining only some of them is how a user loses
 *  their PATH. */
const STARTUP_FILES = [".zshenv", ".zprofile", ".zshrc", ".zlogin"] as const;

/**
 * v1 is zsh, the login shell on this machine.
 *
 * bash and fish emit the same OSC 133 marks with entirely different hook
 * syntax, so the wrapper is per-shell and only zsh's is written. Anything
 * else gets no integration and no dropdown, silently — a terminal exactly
 * as it is today, which is a far better outcome than a wrapper guessing at
 * a shell it does not know.
 *
 * `-zsh` is matched because that is how a login shell spells its own argv[0].
 */
export function isZsh(shell: string | undefined): boolean {
  if (shell === undefined || shell === "") return false;
  const name = shell.slice(shell.lastIndexOf("/") + 1);
  return name === "zsh" || name === "-zsh";
}

/** A path as shell source: single-quoted, with any embedded quote closed,
 *  escaped and reopened. Nothing inside single quotes is expanded, so this
 *  is safe for a home directory containing a space, a `$` or a backtick. */
function quote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

/**
 * The chaining preamble every wrapper file starts with.
 *
 * The order matters and is the reason all four files exist. zsh reads
 * `$ZDOTDIR/.zshenv` first — so ZDOTDIR is pointed back at the user's real
 * directory, their file is sourced, and then ZDOTDIR is restored to
 * Jarvis's. Without that restore, zsh would go looking for .zprofile and
 * .zshrc in the user's directory, find the real ones, and never read the
 * wrapper's — the hook would silently never install.
 *
 * `JARVIS_ZDOTDIR` is captured rather than hard-coded so the wrapper keeps
 * working if it is ever moved, and re-derived defensively in every file in
 * case a user's own `.zshenv` reassigns ZDOTDIR.
 */
function chain(realZdotdir: string, name: string): string[] {
  const real = quote(realZdotdir);
  const file = quote(`${realZdotdir}/${name}`);
  return [
    "# Generated by Jarvis. Edits are overwritten; your own dotfiles are never modified.",
    "JARVIS_ZDOTDIR=${JARVIS_ZDOTDIR:-$ZDOTDIR}",
    `ZDOTDIR=${real}`,
    `[[ -r ${file} ]] && source ${file}`,
    'ZDOTDIR="$JARVIS_ZDOTDIR"',
  ];
}

/**
 * The OSC 133 hooks, and the command log that gives ranking its directory
 * affinity.
 *
 * `A` marks the start of the prompt, `B` its end — the column the typed
 * command begins at, which is the whole reason for this file. `C` says a
 * command is running, so the dropdown closes; `D` carries its exit status.
 *
 * The prompt-end mark is appended to whatever PS1 the user's own .zshrc
 * left behind, never assigned over it: their prompt is theirs.
 *
 * Everything here is guarded or non-fatal. A shell that cannot load
 * add-zsh-hook, or a log that cannot be written, leaves a working terminal
 * with no autocomplete — the failure mode this design insists on.
 */
function hooks(): string[] {
  return [
    "",
    "if [[ -o interactive ]]; then",
    "  zmodload zsh/datetime 2>/dev/null",
    "  __jarvis_osc() { printf '\\e]133;%s\\a' \"$1\" }",
    "  __jarvis_osc7() { printf '\\e]7;file://%s\\a' \"$1\" }",
    "  __jarvis_precmd() {",
    "    local __jarvis_exit=$?",
    '    __jarvis_osc "D;$__jarvis_exit"',
    '    __jarvis_osc7 "$PWD"',
    "    __jarvis_osc 'A'",
    "  }",
    "  __jarvis_preexec() {",
    '    __jarvis_osc "C;${1}"',
    `    if [[ -n "$${JARVIS_COMMAND_LOG_ENV}" ]]; then`,
    `      print -r -- "\${EPOCHSECONDS}"$'\\t'"\${PWD}"$'\\t'"\${1}" >> "$${JARVIS_COMMAND_LOG_ENV}" 2>/dev/null`,
    "    fi",
    "  }",
    "  if autoload -Uz add-zsh-hook 2>/dev/null; then",
    "    add-zsh-hook precmd __jarvis_precmd",
    "    add-zsh-hook preexec __jarvis_preexec",
    "  fi",
    "  PS1=\"${PS1}\"$'\\e]133;B\\a'",
    "fi",
    "",
  ];
}

/**
 * The contents of the wrapper directory, keyed by file name.
 *
 * Pure — it takes the user's real ZDOTDIR and returns text. The chaining it
 * produces is the single riskiest mechanical piece of this feature, which
 * is why it is a value a test can read rather than something only a real
 * login shell could reveal.
 */
export function zshWrapperFiles(realZdotdir: string): Record<string, string> {
  const files: Record<string, string> = {};
  for (const name of STARTUP_FILES) {
    const lines = chain(realZdotdir, name);
    if (name === ".zshrc") lines.push(...hooks());
    files[name] = `${lines.join("\n")}\n`;
  }
  return files;
}

export type ZshIntegrationDeps = {
  /** The user's login shell — `$SHELL`. Integration is zsh-only. */
  shell: string | undefined;
  /** `terminal.completion.enabled`. False installs nothing at all: one
   *  switch, no half-state. */
  enabled: boolean;
  /** Where the wrapper is written — Jarvis's own directory, never the
   *  user's. */
  dir: string;
  /** The user's real ZDOTDIR: `$ZDOTDIR` if they set one, else `$HOME`. */
  realZdotdir: string;
  write: (path: string, contents: string) => Promise<void>;
};

/**
 * Writes the wrapper and returns the directory to hand the child shell as
 * ZDOTDIR — or undefined when there is to be no integration.
 *
 * Undefined is a first-class outcome, not an error: disabled, not zsh, or
 * a directory that could not be written all mean the same thing to the
 * terminal, which is that it behaves exactly as it does today. There is no
 * dialog and nothing logged to the user, because a failure here costs an
 * autocomplete and nothing else.
 */
export async function installZshIntegration(
  deps: ZshIntegrationDeps,
): Promise<string | undefined> {
  if (!deps.enabled) return undefined;
  if (!isZsh(deps.shell)) return undefined;

  try {
    const files = zshWrapperFiles(deps.realZdotdir);
    for (const [name, contents] of Object.entries(files)) {
      await deps.write(`${deps.dir}/${name}`, contents);
    }
    return deps.dir;
  } catch {
    // No wrapper, so no ZDOTDIR, so no marks, so no dropdown.
    return undefined;
  }
}
